apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false

  - name: Alpha-0 GraphQL
    uid: alpha0-graphql
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://alpha-0:8080/graphql
    editable: false

  - name: Alpha-1 GraphQL
    uid: alpha1-graphql
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://alpha-1:8080/graphql
    editable: false

  - name: Alpha-2 GraphQL
    uid: alpha2-graphql
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://alpha-2:8080/graphql
    editable: false
